version: 2

jobs:
  build:
    working_directory: /go/src/github.com/allcloud-io/clisso
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          command: |
            dep ensure
            make test
            make all
