version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          command: |
            dep ensure
            make test
            make all
